name: Build with Nuitka

on:
  push:
    tags: ['v*']  # 只在打tag时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10']
        include:
          - os: ubuntu-latest
            artifact_name: linux
          - os: macos-latest
            artifact_name: macos
            icon: --macos-create-app-bundle
          - os: windows-latest
            artifact_name: windows

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        pip install -r requirements.txt
        
    - name: Build with Nuitka
      run: |
        python -m nuitka \
          --standalone \
          --onefile \
          --follow-imports \
          --remove-output \
          ${{ matrix.icon }} \
          --output-dir=dist/${{ matrix.artifact_name }} \
          main.py  # 替换为你的入口文件
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}-binary
        path: dist/${{ matrix.artifact_name }}
