name: Build and Release

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag (e.g. v1.0.0), leave empty for test build'
        required: false
        default: ''

env:
  PROJECT_NAME: "pyping"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
        python-version: ["3.10"]
        include:
          - os: ubuntu-22.04
            platform: linux-x64
            ext: ""
          - os: windows-2022
            platform: windows-x64
            ext: ".exe"
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Determine version
      id: version
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.version_tag }}" ]]; then
          VERSION="${{ github.event.inputs.version_tag }}"
          VERSION="${VERSION//v/}"
        elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
          VERSION="${GITHUB_REF#refs/tags/v}"
        else
          VERSION="0.0.0"
        fi
        echo "version=${VERSION}" >> $GITHUB_OUTPUT

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka==2.0.0
        pip install -r requirements.txt

    - name: Linux Build
      if: runner.os == 'Linux'
      run: |
        mkdir -p dist
        VERSION="${{ steps.version.outputs.version }}"
        output_name="pyping-linux-x64-$VERSION"
        
        # 获取证书路径
        CERT_PATH=$(python -c "import certifi; print(certifi.where())")
        SITE_PACKAGES=$(python -c "import site; print(site.getsitepackages()[0])")
        
        python -m nuitka \
          --standalone \
          --onefile \
          --follow-imports \
          --include-package=dns \
          --include-package=ping3 \
          --include-package=tcppinglib \
          --include-package=requests \
          --include-package=tqdm \
          --include-package=certifi \
          --include-data-file=$CERT_PATH=certifi/cacert.pem \
          --include-data-dir=$SITE_PACKAGES/certifi=certifi \
          --remove-output \
          --lto=yes \
          --assume-yes-for-downloads \
          --output-dir=dist \
          --output-filename="$output_name" \
          pyping.py
        
        chmod +x "dist/$output_name"
        cd dist
        shasum -a 256 * > checksums.txt

    - name: Windows Build
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path dist
        $VERSION = "${{ steps.version.outputs.version }}"
        $output_name = "pyping-windows-x64-$VERSION.exe"
        
        # 获取证书路径和正确的certifi目录路径
        $CERT_PATH = python -c "import certifi; print(certifi.where())"
        $CERTIFI_DIR = python -c "import certifi, os; print(os.path.dirname(certifi.__file__))"
        
        # 验证路径是否存在
        if (-not (Test-Path -Path $CERTIFI_DIR)) {
            Write-Host "Certifi directory not found at: $CERTIFI_DIR"
            exit 1
        }
        
        python -m nuitka `
          --standalone `
          --onefile `
          --follow-imports `
          --include-package=dns `
          --include-package=ping3 `
          --include-package=tcppinglib `
          --include-package=requests `
          --include-package=tqdm `
          --include-package=certifi `
          --include-data-file="$CERT_PATH=certifi/cacert.pem" `
          --include-data-dir="$CERTIFI_DIR=certifi" `
          --remove-output `
          --lto=yes `
          --assume-yes-for-downloads `
          --output-dir=dist `
          --output-filename="$output_name" `
          pyping.py
        
        Set-Location dist
        Get-ChildItem | ForEach-Object {
          $hash = (Get-FileHash $_ -Algorithm SHA256).Hash
          "$($_.Name)  $hash" | Out-File -Append checksums.txt
        }

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}
        path: dist/
        retention-days: 3

  create-release:
    needs: build
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: "*"
        merge-multiple: true

    - name: Get release version
      id: release-version
      shell: bash
      run: |
        VERSION="${GITHUB_REF#refs/tags/v}"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: "PyPing ${{ steps.release-version.outputs.version }}"
        body: |
          ### Build Artifacts
          - **Windows**: pyping-windows-x64-${{ steps.release-version.outputs.version }}.exe
          - **Linux**: pyping-linux-x64-${{ steps.release-version.outputs.version }}
          
          ### Verification
          ```sh
          # Linux
          shasum -a 256 <file>
          
          # Windows
          certutil -hashfile <file> SHA256
          ```
        files: |
          artifacts/**/*
        draft: false
        prerelease: ${{ contains(github.ref, '-') }}